### ISSUE TITLE
Team profiles

### ISSUE THREAD

**Issue by adieyal** [OpenUpSA/openupsa.github.io#196]
Urgently add profile photos for Naeelah and Chantal

**Comment by guushoekman** [comment]
Was hoping to take their photo to match the others. Will probably get around to that late next week (Julia and Jameelah don't have a proper photo either). Chantal will need another one. How urgently do you need this?

**Comment by adieyal** [comment]
I need it soon, even if the photos are temporary. You can use the ones on this slide as fill-ins: https://docs.google.com/presentation/d/1hCQD6Tt5mUsKxgGQwOSl9kd3P1DTopAe2kX_M8FZDbI/edit#slide=id.g2846bed6de_0_1956
