### ISSUE TITLE
Funders on website

### ISSUE THREAD

**Issue by adieyal** [OpenUpSA/openupsa.github.io#251]
We need to separate current funders from past funders
https://openup.org.za/about.html

**Comment by schalkventer** [comment]
Will create Trello ticket.

**Comment by AliciadW** [comment]
@schalkventer and @adieyal Please see:
https://github.com/OpenUpSA/openupsa.github.io/pull/287

**Comment by AliciadW** [comment]
@schalkventer if you and Adi are happy can we close this issue?
