### ISSUE TITLE
My articles are not showing up on my profile page

### ISSUE THREAD

**Issue by adieyal** [OpenUpSA/openupsa.github.io#282]
https://openup.org.za/team/adi.html

Also, the layout of the articles that are there is buggy

**Comment by schalkventer** [comment]
Thanks for the heads up @adieyal. It seems that the current styling does not allow uploading of images that are not exact dimensions as the others. Should be easy enough to fix with `background-image` or `display: flex`. 

Will add a ticket to Trello for @AliciadW . 👍

**Comment by AliciadW** [comment]
@schalk and @adi there is a rule in the code that allows only 4 articles on a team member's page. Should we increase or remove completely?

**Comment by adi** [comment]
Hi there,

I'm sure it's not @adi who you're looking for. This is my handle on GitHub
for a good number of years.

Have fun,
Adrian

**Comment by schalkventer** [comment]
Thanks @adi. @AliciadW I think you meant @adieyal ;)

**Comment by AliciadW** [comment]
Indeed, apologies for that :-)

**Comment by AliciadW** [comment]
@schalkventer please see #289

**Comment by AliciadW** [comment]
@schalkventer if you and Adi are happy can we close this issue?
